### ISSUE TITLE
Error when ordering a single pixel from command line

### ISSUE THREAD

**Issue by loicdtx** [loicdtx/landsat-extract-gee#1]
Running 

```bash
gee_extract.py -s LT5 -b 1980-01-01 -lon -89.8107 -lat 20.4159  -db /tmp/gee_db.sqlite -site uxmal_point -table col_1
```

Returns

```console
Traceback (most recent call last):
  File "/Users/ldutrieux/.virtualenvs/gee/bin/gee_extract.py", line 95, in <module>
    main(**vars(parsed_args))
  File "/Users/ldutrieux/.virtualenvs/gee/bin/gee_extract.py", line 22, in main
    dict_list_1 = relabel(dict_list_0, sensor)
  File "/Users/ldutrieux/git/landsat-extract-gee/geextract/__init__.py", line 241, in relabel
    dl_out = [change_keys(d, BANDS_TO_COLORS[sensor]) for d in dl]
  File "/Users/ldutrieux/git/landsat-extract-gee/geextract/__init__.py", line 241, in <listcomp>
    dl_out = [change_keys(d, BANDS_TO_COLORS[sensor]) for d in dl]
  File "/Users/ldutrieux/git/landsat-extract-gee/geextract/__init__.py", line 240, in change_keys
    return dict((dr[key], value) for (key, value) in d.items())
  File "/Users/ldutrieux/git/landsat-extract-gee/geextract/__init__.py", line 240, in <genexpr>
    return dict((dr[key], value) for (key, value) in d.items())
KeyError: 'longitude'
```

**Comment by albe82** [comment]
Hi, I got the same error (error extracting site 'longitude') when using batch process to extract multiple pixels.

I override it by incorporating radius of 5 m, but then I got values for two pixels (values are slightly different) for each (buffered) point. For now I just took the average of those two....

Great tool, tnx.

Regards, 
Alen

**Comment by loicdtx** [comment]
Thanks for the report @albe82, I'll try to work on a fix soon.
